### ISSUE TITLE
guard crash

### ISSUE THREAD

**Issue by orlin** [oliamb/guard-compass#1]
Guard crashes when I change a sass file:

  ~/.rvm/gems/ree-1.8.7-2010.02/gems/compass-0.10.6/lib/compass/commands/update_project.rb:40:in `check_for_sass_files!': Nothing to compile. If you're trying to start a new project, you have left off the directory argument. (Compass::Error)

I can still work without this - using padrino + guard-livereload.  Is a fix planned for the 1.0 roadmap (pending the use compass config)?

**Comment by oliamb** [comment]
Thank You for the report. Yes, even before that :-)

I will look into that during the week-end.

**Comment by oliamb** [comment]
Can you give me an excerpt of your compass config file and Guardfile?

**Comment by oliamb** [comment]
This failure probably came from the fact that your Compass 'working directory' is not the same than Guard 'working directory'. This result in Compass not finding its configuration file and sending back this exception.

I added two options to Guard::Compass which should let you resolve this problem. Playing with one or both should solve your issue.
- :configuration_file let you point to your... yes
- :workdir let you specify your compass 'home'

In your case, this should solve your problem:

```
guard 'compass', :workdir => 'my_compass_home' do
  watch('^my_compass_home/src/(.*)')
end
```

In case you also have your Compass config file in a non-standard place, you can try:

```
guard 'compass', :workdir => 'my_compass_home', :configuration_file => 'my_compass_home/conf/config.rb' do
  watch('^my_compass_home/src/(.*)')
end
```

I know that workdir and configuration_file use two different naming convention, but they reflect the name of the same options in Compass. Do you think I should use only one? If yes, which one do you prefer (I vote for the longest, more ruby style)?

I Hope it will solve your issue. The patch is currently in my repository and will be included into the next gem release (0.1.0). If this is not enough, please provide me some more information about your directory structure and where is located your Guardfile and your Compass files.

**Comment by oliamb** [comment]
Added test and updated error message in case
of Bad Compass configuration file.

Closed by 21c2e7b55e0fe96399211a57af944bf1e49a46a2.

**Comment by orlin** [comment]
Thanks for fixing this.  It works for me without setting the :workdir (seems like :configuration_file is enough).  I'm guessing you get the porject_path form where the Guardfile is (the project's root) which is perfect - that's the only thing I'm not setting with the config/compass.rb (have the web framework do it).  The paths are relative to that, but set through config vars (in my case: sass_dir = "app/stylesheets" and css_dir = "public/stylesheets") - maybe :workdir makes sense for generated starter projects but :configuration_file is all that's needed, imo.

**Comment by oliamb** [comment]
Ok perfect. Specifying the working dir might be interesting if your Guard root is not the same as the compass root and that you plan to run compass command on even day and the guard command on odd day... I agree, this is a limit case.

Thanks for the feedback :-)
