### ISSUE TITLE
config.rb and default css_dir

### ISSUE THREAD

**Issue by Granze** [oliamb/guard-compass#10]
Hi, I'm trying to setup a new project with guard-compass, but it seems that my configuration file isn't used properly.

My Guardfile:

``` ruby
guard 'compass', :configuration_file => 'config.rb' do
  watch(%r{(.*)\.s[ac]ss$})
end
```

My config.rb (placed in the root of the project)

``` ruby
http_path = "/"
css_dir = "css"
sass_dir = "sass"
images_dir = "img"
javascripts_dir = "js"
output_style = :compressed
relative_assets= true
line_comments = false
```

When I change a scss file in my sass folder, guard creates another config.rb file in that directory and 2 .css: one in the css folder, one in the sass folder. That's because the created config.rb looks like this

``` ruby
http_path = "/"
css_dir = "."
sass_dir = "."
images_dir = "img"
javascripts_dir = "js"
output_style = :compressed
relative_assets=true
line_comments = false
```

The same issue occoured when I modify sass file in other directories.

If I change these generated config.rb to match my needs it works, but I don't really want to have multilple config.rg in my project.

P.S. Im on windows 7

**Comment by rymai** [comment]
Hi, do you still have the issue?

If yes, please [open a new issue in the maintained repo](https://github.com/guard/guard-compass/issues).

In both cases, don't forget to close this issue, thanks!

**Comment by Granze** [comment]
Hi, I switched to grunt for this task so I didn't tried to investigate more.

**Comment by rymai** [comment]
Ok, thanks for the reply!
