### ISSUE TITLE
Problem with compass sprite generator

### ISSUE THREAD

**Issue by renanveroneze** [oliamb/guard-compass#11]
``` sass
@import "icons/*.jpg"
```

Returns this error:  

```
File to import not found or unreadable: icons/*
```

---

My config.rb file

``` ruby
http_path = ""
css_dir = "assets/css"
sass_dir = "assets/sass"
images_dir = "assets/img"
javascripts_dir = "assets/js"
output_style = :compressed
relative_assets = false
line_comments = false
```

---

My Worktree

```
.
| -- > assets
|   | -- > img
|   |   | -- > icons
|   |
|   | -- > sass
|   |   | -- > config.rb
|   |   | -- > file.sass
|   |
|   | -- > css
|   |   | -- > file.css
```

---

My Guardfile

``` ruby
guard 'compass', :workdir => '', :configuration_file => 'assets/sass/config.rb' do
   watch('^(.*)\.sass')
end
```

**Comment by rymai** [comment]
Hi,

Do you still have this issue? If yes, please ensure that `compass watch` works as expected (if not, that's probably a Compass config issue, not a guard-compass one).

If the issue doesn't look like a Compass config issue, [please open a new issue in the maintained repo](https://github.com/guard/guard-compass/issues).

In both cases, don't forget to close this issue, thanks!

**Comment by renanveroneze** [comment]
Hi @rymai, 

I found a solution, but at the moment I cannot remember there.
Anywhere problem, I come back to warn.
Thank you for your attention.

[Closed]
